// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDp3shRX4plFp91D3Yr1UJEu5pW8emCedM',
    appId: '1:687571036281:web:5cff59d7284eca28d04ca8',
    messagingSenderId: '687571036281',
    projectId: 'codegenius-instagram-clone',
    authDomain: 'codegenius-instagram-clone.firebaseapp.com',
    storageBucket: 'codegenius-instagram-clone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHovhf4Xm5MMIvcTwbJnxUWP1S0ExmWfc',
    appId: '1:687571036281:android:7ff477fda7a93634d04ca8',
    messagingSenderId: '687571036281',
    projectId: 'codegenius-instagram-clone',
    storageBucket: 'codegenius-instagram-clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIutpQFCloAGPxI_BY_dpRm4A90s6CzPU',
    appId: '1:687571036281:ios:0080cb9a7ca4e3cdd04ca8',
    messagingSenderId: '687571036281',
    projectId: 'codegenius-instagram-clone',
    storageBucket: 'codegenius-instagram-clone.appspot.com',
    iosClientId: '687571036281-io53uhsccibb7jq42ghnc7ecfq8k8bea.apps.googleusercontent.com',
    iosBundleId: 'com.codegenius.flutterInstagramClone',
  );
}
